import 'dart:convert';
import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:collection/collection.dart';
import 'package:easy_wellness_biz_app/constants/misc.dart';
import 'package:easy_wellness_biz_app/models/location/geo_position.model.dart';
import 'package:easy_wellness_biz_app/models/nearby_service/db_nearby_service.model.dart';
import 'package:easy_wellness_biz_app/models/place/db_place.model.dart';
import 'package:easy_wellness_biz_app/models/review/db_review.model.dart';
import 'package:easy_wellness_biz_app/services/gmp_service/find_nearby_places.service.dart';
import 'package:easy_wellness_biz_app/widgets/weekly_schedule_settings/edit_weekly_schedule_screen.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:geoflutterfire/geoflutterfire.dart';
import 'package:http/http.dart' as http;

Future<void> seedPlacesAndServices() async {
  final geo = Geoflutterfire();
  final db = FirebaseFirestore.instance;
  final places = await findNearbyPlaces();
  print('Seeding ${places.length} places and services for each...');
  await Future.wait(places.mapIndexed((placeIndex, place) async {
    final GeoFirePoint location = geo.point(
      latitude: place.geometry.location.lat,
      longitude: place.geometry.location.lng,
    );
    final placeRef = db.collection('places').doc(place.placeId);
    final servicesRef =
        placeRef.collection('services').withConverter<DbNearbyService>(
              fromFirestore: (snapshot, _) =>
                  DbNearbyService.fromJson(snapshot.data()!),
              toFirestore: (service, _) => service.toJson(),
            );
    final address =
        '${place.vicinity}, ${place.plusCode?.compoundCode.substring(8) ?? ''}';
    final geoPos = GeoPosition(
      geohash: location.data['geohash'],
      geopoint: location.data['geopoint'],
    );
    await placeRef
        .withConverter<DbPlace>(
          fromFirestore: (snapshot, _) => DbPlace.fromJson(snapshot.data()!),
          toFirestore: (place, _) => place.toJson(),
        )
        .set(DbPlace(
          name: _clinicNames[placeIndex],
          geoPosition: geoPos,
          ownerId: FirebaseAuth.instance.currentUser!.uid,
          workingHours: defaultWeeklySchedule,
          email: 'versatileclinic@clinic.biz.com',
          phoneNumber: '(+84) 12 345 67 89',
          address: address,
          status: place.businessStatus.toLowerCase(),
          minuteIncrements: 30,
          minLeadHours: 24,
          maxLeadDays: 365,
        ));
    final randomSource = Random();
    final nReviews = 4;
    await Future.wait(
      specialties.mapIndexed(
        (specialtyIndex, specialty) async {
          final ratingPoints = List.generate(
            nReviews,
            (_) => _getRandomIntInRange(randomSource, 1, 5).toDouble(),
          );
          final serviceRef = await servicesRef.add(DbNearbyService(
            rating: ratingPoints.average,
            ratingsTotal: nReviews,
            duration: (_getRandomIntInRange(randomSource, 15, 180) ~/ 15) * 15,
            description:
                'Half section of Italian or French bread with garlic butter, containing ham, provel or provolone cheese, topped with paprika, then toasted. Doner kebab is meat cooked on a vertical spit, normally veal or beef but also may be a mixture of these with lamb, and sometimes chicken that may be served wrapped in a flatbread such as lavash or pita or as a sandwich. Slices of cheese (typically Cheddar) and pickle (a sweet, vinegary chutney with the most popular brand being Branston), sandwiched between two slices of bread.',
            specialty: specialty,
            serviceName: '${_serviceAdjectives[specialtyIndex]} $specialty',
            priceTag: PriceTag(
              type: PriceType.startingAt,
              value: _getRandomIntInRange(randomSource, 15, 1000),
            ),
            placeName: _clinicNames[placeIndex],
            placeId: place.placeId,
            address: address,
            geoPosition: geoPos,
            minuteIncrements: 30,
            minLeadHours: 24,
            maxLeadDays: 365,
          ));
          await Future.wait(List.generate(
            nReviews,
            (reviewIndex) => serviceRef
                .collection('reviews')
                .withConverter<DbReview>(
                  fromFirestore: (snapshot, _) =>
                      DbReview.fromJson(snapshot.data()!),
                  toFirestore: (review, _) => review.toJson(),
                )
                .add(DbReview(
                  creatorId: UniqueKey().toString(),
                  creatorName: _fullnames[randomSource.nextInt(160)],
                  placeId: placeRef.id,
                  serviceId: serviceRef.id,
                  rating: ratingPoints[reviewIndex],
                  text: _fakeReviews[randomSource.nextInt(160)],
                  createdAt: Timestamp.fromDate(
                    DateTime.fromMillisecondsSinceEpoch(
                      _getRandomIntInRange(
                              randomSource, 1609434000, 1634031529) *
                          1000,
                    ),
                  ),
                )),
            growable: false,
          ));
        },
      ),
    );
  }));
  print('All done!');
}

// Don't drop millisecondsSinceEpoch here.
int _getRandomIntInRange(Random source, int min, int max) =>
    source.nextInt(max - min + 1) + min;

// [0,1) => [0, max-min) => [min, max)
// double _getRandomDoubleInRange(Random source, double min, double max) =>
//     source.nextDouble() * (max - min) + min;

/// The fake data returned from Faker Cloud at https://fakercloud.com/api is
/// then hard coded into the Dart file where this method is defined.
///
/// Possible values for [property]: 'Hospital', 'Full Name',
/// 'Sandwhich Description'.
void getDataFromFakerCloud(int nRequests, String property) async {
  final fakerAPI = Uri.https(
    'fakercloud.com',
    '/schemas/property',
  );
  final futures = List.generate(
    nRequests,
    (_) => http.post(fakerAPI, body: {'name': property}).then(
      (res) => (jsonDecode(res.body)['results'] as List)
          .map<String>(
            (e) => e.toString(),
          )
          .toList(),
    ),
    growable: false,
  );
  final results = await Future.wait(futures);
  final jsonString = json.encode(results.expand((list) => list).toList());
  print(jsonString);
}

// 160 items
const _fakeReviews = [
  "Form of barbecue in which pork is cooked using a slow cook method until the meat becomes tender enough that it can be \"pulled\", or easily broken into individual pieces",
  "A hot dog wrapped in a beef patty, deep-fried, then covered with chili, a few french fries, and a fried egg",
  "A generic sandwich containing a filling, and a layer of cheese, grilled or fried until the cheese is melted",
  "Especially noted from Beigel Bake in Brick Lane, east London.",
  "Made of ground beef, tomato sauces, spices and many onions and peppers. It is a popular food served at local family gatherings and fund raising benefits, usually made in large quantities.",
  "A cheeseburger with the cheese inside the meat patty rather than on top",
  "A hot dog bun containing a Chicago-style corn-roll tamale, topped with chili",
  "A typical food of Mexico and a kind of bread in Spain. In Mexico, Molletes are prepared with melted cheese and beans with other ingredients, such as salsa, ham or bacon.",
  "A sandwich containing a Denver omelette",
  "A cooked sausage, traditionally grilled or steamed and served in a sliced bun as a sandwich.",
  "Filet américain (steak tartare) with Worcestershire sauce, pickles, onions, peppers and martino sauce",
  "A generic sandwich containing a filling, and a layer of cheese, grilled or fried until the cheese is melted",
  "A brown gravy base and chow mein mixture in a hamburger-style bun",
  "Named for its ingredients: bacon, lettuce and tomato",
  "Vegemite is a dark brown Australian food paste made from used brewers' yeast extract, a by-product of beer manufacturing, various vegetables, wheat and spice additives. It is a spread for sandwiches, toast, crumpets and cracker biscuits as well as a filling for pastries.",
  "Doner kebab is meat cooked on a vertical spit, normally veal or beef but also may be a mixture of these with lamb, and sometimes chicken that may be served wrapped in a flatbread such as lavash or pita or as a sandwich.",
  "Lettuce and mayonnaise",
  "Originated in New Orleans' Italian-American community, meats, cheeses, and olive salad on a round bun",
  "A square of thin chocolate bar topped with a toasted marshmallow between two squares of graham cracker",
  "Meatballs in marinara sauce, with melted Parmesan or provolone cheese, on a long bun or section of Italian loaf. Might include Italian-style accompaniments such as bell peppers, basil, or Italian-dressed lettuce",
  "A tamale inserted in a Mexican bread, bolillo, easy to find in Mexico City streets in the morning, also called torta de tamal",
  "A slice of toast with ham, a maraschino cherry in the middle of a pineapple slice, and cheese, grilled from above, so the cheese starts to melt",
  "Triangular white bread with the crusts removed, with fillings such as tuna and olive and prosciutto, served in Italian bars throughout the day",
  "Single, open-faced, containing butter as the common ingredient, with sweet or savory toppings depending on the meal",
  "Grilled chorizo, usually served on a crusty roll with salsa-type condiments, such as pebre, salsa criolla or chimichurri. Morcipán is a variety of this using black pudding or blood sausage.",
  "A hot dog wrapped in a beef patty, deep-fried, then covered with chili, a few french fries, and a fried egg",
  "Vanilla ice cream between thin biscuits, cookies or slices of cake, normally chocolate",
  "Breaded, deep-fried pork cutlet (tonkatsu)",
  "Made with single-, double- or triple-layered, buttered, thin white bread with crust removed, toasted or untoasted, contains thinly sliced meat and may include ham, eggs, cheese, tomatoes, green peppers, lettuce, olives, and sometimes other vegetables, even asparagus.",
  "Thinly sliced churrasco-style steak, or lomito-style pork, with tomatoes, green beans and green chiles, served on a round roll",
  "Buttered bread, with jam (traditionally strawberry), normally eaten at lunchtime or as a quick snack, may also be eaten at breakfast or for high tea",
  "Lettuce and mayonnaise",
  "Round bread (bread bagnats) opened in two, rub each half with a clove of garlic, moisten with vinegar, olive oil, salt and pepper, the choice can be added green salad, tomatoes, hard boiled eggs, tuna, anchovies, cucumbers, fava beans, small fresh artichokes, green peppers, radishes, fresh spring onions, basil and black olives of Nice. Serve chilled.",
  "A cheeseburger with the cheese inside the meat patty rather than on top",
  "Corned beef with mustard, usually on rye bread",
  "A tamale inserted in a Mexican bread, bolillo, easy to find in Mexico City streets in the morning, also called torta de tamal",
  "Consists of a single slice of bread with one or more food items on top. See also pizza.",
  "Meat, cheese, lettuce and tomato, between flattened, fried green plantains (instead of bread), with garlic-flavored mayonnaise",
  "A stuffed and fried bread roll (sometimes called stuffed pistolettes) in the Cajun areas around Lafayette. Also refers to a type of submarine shaped bread about half the size of a baguette that is popular in New Orleans for Vietnamese bánh mì and other sandwiches.",
  "Although there are numerous variations, the main distinction is a combination of three meats, typically grilled, such as beef (usually churrasco steak or cube steak), roast pork (pernil), chicken, and ham. Condiments may include some combination of mustard, ketchup, and mayonnaise, often combined to create a “special” sauce. Popular toppings include thin crispy fried potato sticks or shoe string potatoes, thinly sliced cabbage, lettuce, onion, tomato, pickles, and Swiss cheese. The sandwich is often finished in a sandwich press until bread is toasted.",
  "Vegemite is a dark brown Australian food paste made from used brewers' yeast extract, a by-product of beer manufacturing, various vegetables, wheat and spice additives. It is a spread for sandwiches, toast, crumpets and cracker biscuits as well as a filling for pastries.",
  "Roast beef on a caraway kaiser roll",
  "In the United States it is usually made with American cheese, and often served toasted alongside tomato soup or with sliced tomato inside. When toasted (pictured), it is commonly referred to as a \"grilled cheese sandwich\".",
  "A generic sandwich served on a long French or Italian roll which may contain a wide variety of sliced meats, vegetables, and condiments, including lettuce, tomato, sweet peppers, onions, olives, and/or mushrooms. Also known regionally as a hero, a hoagie, a grinder, or a zep, among other names. In the United Kingdom it is named a baguette, after the French bread used to make it.",
  "A simple Argentine sandwich, traditionally filled with cheese, cured meat, tomato and mayonnaise. The term pebete actually refers to the bread used for the sandwich; a soft oval bun with a spongy inside, and a thin toasted crust.",
  "Birote bread (bolillo) sliced open on one side, and filled with chopped, fried pork, and sometimes chicken or shredded meat, beans and cheese, served submerged in a sauce made mostly of a dried chile de árbol.",
  "Half section of Italian or French bread with garlic butter, containing ham, provel or provolone cheese, topped with paprika, then toasted",
  "A hot dog wrapped in a beef patty, deep-fried, then covered with chili, a few french fries, and a fried egg",
  "Buttered bread, with jam (traditionally strawberry), normally eaten at lunchtime or as a quick snack, may also be eaten at breakfast or for high tea",
  "A deli-style sandwich similar to the hoagie, often contains french fries, with other variations, prepared with masala steak, chicken, polony, Vienna sausages, calamari, fish, or chargrilled steak",
  "Vegan version of the BLT: Smoky baked tempeh, lettuce, tomato and avocado served sourdough toasted bread",
  "Many types of vegetables are used to prepare vegetable sandwiches.",
  "A French baguette with butter and ham. Also known as \"Parisien\", it is the most popular sandwich in France.",
  "Leberkäse is a meatloaf-like dish which, despite the name, contains neither liver nor cheese. It is commonly served on a Kaiser roll with mustard.",
  "Served on a bun, with chopped or sliced meat (pulled pork, beef or chicken typically), and sometimes topped with coleslaw",
  "Corned beef with mustard, usually on rye bread",
  "Buttered bread, with jam (traditionally strawberry), normally eaten at lunchtime or as a quick snack, may also be eaten at breakfast or for high tea",
  "Generally served hot, and often eaten with ketchup or brown sauce",
  "A patty dish popular in the Balkan region of Southeastern Europe, a sandwich utilizes the Pljeskavica patty and bread.",
  "Peanut butter and marshmallow creme. Pictured is a fluffernutter sandwich prior to being assembled.",
  "Consists of a single slice of bread with one or more food items on top. See also pizza.",
  "\"Pita gyro\" or \"psomaki gyro\", depending on the type of bread used, includes meat roasted on a vertical spit, with tomato, raw, often red onion and optional yogurt sauce, wrapped in pita or sandwich bread.",
  "A bun with wet-cured ham, linguiça, and cheese, sauced with butter or margarine, piri-piri, and port wine, whiskey, cognac or brandy",
  "In the United States it is usually made with American cheese, and often served toasted alongside tomato soup or with sliced tomato inside. When toasted (pictured), it is commonly referred to as a \"grilled cheese sandwich\".",
  "Made of ground beef, tomato sauces, spices and many onions and peppers. It is a popular food served at local family gatherings and fund raising benefits, usually made in large quantities.",
  "A crusty bread loaf typically filled with fried seafood or roast beef.",
  "Typically a scrambled or fried egg, cheese, and a sausage patty or other breakfast meat served on a biscuit or English muffin",
  "A hamburger or cheeseburger with a glazed doughnuts instead of a bun",
  "Sandwiches prepared with thinly sliced or pressed salted and dried beef. Some chipped beef is smoked to add flavor.",
  "Leberkäse is a meatloaf-like dish which, despite the name, contains neither liver nor cheese. It is commonly served on a Kaiser roll with mustard.",
  "Roast pork, ham, mustard, Swiss cheese, and dill pickles served on sweet bread.",
  "A bun filled with a mixture of (usually) loose meat, cabbage, and cheese. The fillings are baked inside the bread, similar to a kolache. Popular in the Midwestern United States, especially Nebraska.",
  "A hot melted cheese sauce, poured over slices (or other pieces) of toasted bread. Or the hot cheese sauce may be served in a bowl accompanied by the toast.",
  "Essentially a miniature hamburger about three inches in diameter, but may contain other ingredients besides a hamburger patty",
  "A slice of toast with ham, a maraschino cherry in the middle of a pineapple slice, and cheese, grilled from above, so the cheese starts to melt",
  "Round bread (bread bagnats) opened in two, rub each half with a clove of garlic, moisten with vinegar, olive oil, salt and pepper, the choice can be added green salad, tomatoes, hard boiled eggs, tuna, anchovies, cucumbers, fava beans, small fresh artichokes, green peppers, radishes, fresh spring onions, basil and black olives of Nice. Serve chilled.",
  "A brown gravy base and chow mein mixture in a hamburger-style bun",
  "Ground meat, usually beef, cooked with seasoned tomato sauce and served on a round bun.",
  "They are typically prepared with buttered rye bread, Limburger cheese, sliced onion and mustard. Pictured is Limburger cheese and bread.",
  "A typical food of Mexico and a kind of bread in Spain. In Mexico, Molletes are prepared with melted cheese and beans with other ingredients, such as salsa, ham or bacon.",
  "Made with pambazo bread dipped in a red guajillo pepper sauce and filled with potatoes with chorizo.",
  "Usually made with tuna salad and includes ingredients such as mayonnaise and celery. Other common variations include the tuna boat and tuna melt.",
  "A hot melted cheese sauce, poured over slices (or other pieces) of toasted bread. Or the hot cheese sauce may be served in a bowl accompanied by the toast.",
  "A simple and common German sandwich prepared with thin slices of lunch meat or sausage. Sometimes butter is added to add flavor.",
  "Often open-faced, sliced turkey on white bread drenched in turkey gravy, often served with mashed potatoes. These are sometimes served at Hofbrau-style restaurants.",
  "A bun with wet-cured ham, linguiça, and cheese, sauced with butter or margarine, piri-piri, and port wine, whiskey, cognac or brandy",
  "Sliced ham and cheese (usually Emmental or Gruyère) between slices of French toast and batter-fried. In some regions it is sprinkled with powdered sugar and served with jelly or jam). In other regions (New England), it is served savory with French mustard and no powdered sugar.",
  "Vanilla ice cream between thin biscuits, cookies or slices of cake, normally chocolate",
  "A ground beef patty, often with vegetables, sauces and other meats, usually on a round bun.",
  "Open-faced with turkey and bacon, topped with mornay sauce, and baked or broiled",
  "A simple and common German sandwich prepared with thin slices of lunch meat or sausage. Sometimes butter is added to add flavor.",
  "Triangular white bread with the crusts removed, with fillings such as tuna and olive and prosciutto, served in Italian bars throughout the day",
  "Form of barbecue in which pork is cooked using a slow cook method until the meat becomes tender enough that it can be \"pulled\", or easily broken into individual pieces",
  "Peanut butter, banana, and bacon inside of two slices of bread",
  "Triangular white bread with the crusts removed, with fillings such as tuna and olive and prosciutto, served in Italian bars throughout the day",
  "Sausages, may be pork, beef or vegetarian. Served with red sauce, brown sauce or no sauce at all.",
  "Kielbasa sausage in a bun, covered with french fries, barbecue sauce (or hot sauce), and coleslaw",
  "A cold meal originating in the United Kingdom, commonly served in pubs. Its core components are (cheddar) cheese, ploughman's pickle and bread. It is traditionally eaten with beer.",
  "A triple-decker sandwich made with sliced turkey or chicken, bacon, tomato and lettuce, usually contains mayonnaise",
  "A thick-sliced, toasted, open-faced sandwich, it usually contains hamburger patties or ham, but other meat, such as deep-fried pork tenderloin, grilled or fried chicken breast, and fried fish filets, can be used. The meat is topped with french fries and covered with a cheese sauce.",
  "Form of barbecue in which pork is cooked using a slow cook method until the meat becomes tender enough that it can be \"pulled\", or easily broken into individual pieces",
  "An open-faced sandwich on rugbrød, with smoked herring, chives and a raw egg yolk",
  "Stewed pork, chopped finely, and stuffed in mo, a kind of flatbread",
  "Filet américain (steak tartare) with Worcestershire sauce, pickles, onions, peppers and martino sauce",
  "A convenience dish on a variety of bread rolls, containing such breakfast items as sausages, bacon, white or black pudding, mushrooms, tomatoes, hash browns and fried eggs, often eaten with ketchup or brown sauce,",
  "Sautéed beef tongue and scrambled eggs, served open-faced ada pav",
  "Although there are numerous variations, the main distinction is a combination of three meats, typically grilled, such as beef (usually churrasco steak or cube steak), roast pork (pernil), chicken, and ham. Condiments may include some combination of mustard, ketchup, and mayonnaise, often combined to create a “special” sauce. Popular toppings include thin crispy fried potato sticks or shoe string potatoes, thinly sliced cabbage, lettuce, onion, tomato, pickles, and Swiss cheese. The sandwich is often finished in a sandwich press until bread is toasted.",
  "Multiple layers of white or light rye bread containing creamy fillings, such as egg and mayonnaise, liver paté, olives, shrimp, ham, various cold cuts, caviar, tomato, cucumber, cheese and smoked salmon",
  "A hamburger, with the patty topped with chili con carne",
  "Filling is typically meat, but can contain a wide range of foods, including sardines, tofu, pâté, or eggs. Served on an airy baguette with pickled carrots, cilantro and peppers.",
  "Melted cheese, roast beef, tomato and pickled cucumber in a hollowed-out French roll",
  "Chopped or shredded, savory donkey meat in a bun, sold in Baoding, Hebei Province as street food, and also in high-end restaurants",
  "Common in Iowa, consists of a mixture of unseasoned ground beef and sauteed onions, sometimes topped with pickles, ketchup and mustard, on a bun",
  "Beef (usually thin cut steak) and cheese",
  "Wet-cured ham, linguiça, fresh sausage (chipolata), steak or other roast meat, topped with melted cheese, a hot thick tomato, and beer sauce",
  "On a piece of dark rye bread, a layer of leverpostej, topped with a slice of salt beef and a slice of meat aspic, topped with raw onion rings and garden cress.",
  "Ground meat, usually beef, cooked with seasoned tomato sauce and served on a round bun.",
  "Coarsely shredded or sliced chicken, sandwiched between two pieces of sliced bread, and completely covered with gravy.",
  "A hot dog wrapped in a beef patty, deep-fried, then covered with chili, a few french fries, and a fried egg",
  "Made with pambazo bread dipped in a red guajillo pepper sauce and filled with potatoes with chorizo.",
  "Grilled chorizo, usually served on a crusty roll with salsa-type condiments, such as pebre, salsa criolla or chimichurri. Morcipán is a variety of this using black pudding or blood sausage.",
  "Crisps and occasionally pickles on white bread",
  "A sandwich made from cured and smoked brisket with yellow mustard, usually on rye bread.",
  "A dated reference to the poor quality of catering on the now-defunct British Rail, refers to any poor-quality sandwich, often stale.",
  "Served on a bun, with chopped or sliced meat (pulled pork, beef or chicken typically), and sometimes topped with coleslaw",
  "A thick-sliced, toasted, open-faced sandwich, it usually contains hamburger patties or ham, but other meat, such as deep-fried pork tenderloin, grilled or fried chicken breast, and fried fish filets, can be used. The meat is topped with french fries and covered with a cheese sauce.",
  "A grilled, over-stuffed submarine roll, containing shaved steak, and topped with salami, melted provolone, sautéed onions, and bell peppers.",
  "Minute and usually grilled, could be filled with anything. Some bars offer a variety of 200 different types of these sandwiches.[citation needed]",
  "Triangular white bread with the crusts removed, with fillings such as tuna and olive and prosciutto, served in Italian bars throughout the day",
  "Type of sandwich that may be ordered at a deli, choices include type of bread (toasted or untoasted,) type of meat (cold cut), type of sliced cheese, vegetable fillings (lettuce, tomato, onion, etc.) and condiments",
  "A cold meal originating in the United Kingdom, commonly served in pubs. Its core components are (cheddar) cheese, ploughman's pickle and bread. It is traditionally eaten with beer.",
  "Open-faced, buttered dark rye bread with cold cuts, pieces of meat or fish, cheese or spreads",
  "A hot dog bun containing a Chicago-style corn-roll tamale, topped with chili",
  "Ham, often with mustard",
  "Consists of a spicy patty which is shallow-fried, onions, and chutney or raita in a hamburger or hot dog bun.",
  "Made with single-, double- or triple-layered, buttered, thin white bread with crust removed, toasted or untoasted, contains thinly sliced meat and may include ham, eggs, cheese, tomatoes, green peppers, lettuce, olives, and sometimes other vegetables, even asparagus.",
  "A triple-decker sandwich made with sliced turkey or chicken, bacon, tomato and lettuce, usually contains mayonnaise",
  "Generally served hot, and often eaten with ketchup or brown sauce",
  "Alternating layers of bread and filling frosted to resemble a layer cake",
  "Peanut butter and marshmallow creme. Pictured is a fluffernutter sandwich prior to being assembled.",
  "Thinly sliced steak and melted cheese in a long roll, also known as a Philadelphia or Philly cheesesteak.",
  "Ham, roasted pork, Swiss cheese, pickles, mustard, and sometimes Genoa salami on Cuban bread, usually pressed and warmed in a plancha",
  "Filling is typically meat, but can contain a wide range of foods, including sardines, tofu, pâté, or eggs. Served on an airy baguette with pickled carrots, cilantro and peppers.",
  "A generic sandwich served on a long French or Italian roll which may contain a wide variety of sliced meats, vegetables, and condiments, including lettuce, tomato, sweet peppers, onions, olives, and/or mushrooms. Also known regionally as a hero, a hoagie, a grinder, or a zep, among other names. In the United Kingdom it is named a baguette, after the French bread used to make it.",
  "Open-faced with turkey and bacon, topped with mornay sauce, and baked or broiled",
  "Typically a scrambled or fried egg, cheese, and a sausage patty or other breakfast meat served on a biscuit or English muffin",
  "Many types of vegetables are used to prepare vegetable sandwiches.",
  "Jam is often used in place of jelly. Also known as a 'PB&J'.",
  "Birote bread (bolillo) sliced open on one side, and filled with chopped, fried pork, and sometimes chicken or shredded meat, beans and cheese, served submerged in a sauce made mostly of a dried chile de árbol.",
  "Originated in New Orleans' Italian-American community, meats, cheeses, and olive salad on a round bun",
  "Wet-cured ham, linguiça, fresh sausage (chipolata), steak or other roast meat, topped with melted cheese, a hot thick tomato, and beer sauce",
  "A ground beef patty, often with vegetables, sauces and other meats, usually on a round bun.",
  "Thinly cut steak, grilled and served on a toasted bun, usually with tomato, avocado and mayonnaise",
  "Peanut butter and marshmallow creme. Pictured is a fluffernutter sandwich prior to being assembled.",
  "Lamb or goat intestines, containing seasoned offal",
  "Canned baked beans on white or brown bread. Sometimes butter is also used.",
  "A dated reference to the poor quality of catering on the now-defunct British Rail, refers to any poor-quality sandwich, often stale.",
  "Consists of a single warmed, hollowed-out loaf of bread filled with one jar of creamy peanut butter, one jar of grape jelly, and a pound of bacon. In 1976, Elvis Presley and some of his friends flew to Colorado to consume them.",
  "A hot dog bun containing a Chicago-style corn-roll tamale, topped with chili",
  "Grilled chorizo, usually served on a crusty roll with salsa-type condiments, such as pebre, salsa criolla or chimichurri. Morcipán is a variety of this using black pudding or blood sausage.",
];

/// 160 items
const _fullnames = [
  "Ora Hintz",
  "Dolores Keebler",
  "Lorraine Torphy",
  "Wade Hettinger",
  "Christie McClure",
  "Robert Quitzon",
  "Gina Pacocha",
  "Dr. Inez Predovic",
  "Grady Romaguera",
  "Sadie Trantow",
  "Miss Marvin Abernathy",
  "Lori O'Reilly Jr.",
  "Jared Mills",
  "Marvin Stoltenberg",
  "Faye Rowe",
  "Dr. Tommie Kuvalis",
  "Dallas Thompson",
  "Nicolas Maggio",
  "Angelina Bogan",
  "Linda Gleichner",
  "Christie Veum",
  "Ms. Kenneth Feil",
  "Mathew Sawayn",
  "Kristie Klein",
  "Esther Rosenbaum",
  "Blanca Rath V",
  "Michael Koelpin",
  "Ernesto Ondricka",
  "Nicolas Okuneva",
  "Ralph Weber MD",
  "Madeline O'Kon",
  "Christopher Kassulke",
  "Bryant Jakubowski PhD",
  "Chad Haley",
  "Joanne Thompson",
  "Dr. Dominic Hoppe",
  "Craig Bechtelar",
  "Alexis Feest",
  "Levi Kemmer MD",
  "Larry Lakin",
  "Gilberto Borer",
  "Kristie Kassulke",
  "Aaron Yundt II",
  "Jeannie Stehr",
  "Gertrude Kshlerin",
  "Scott Reinger",
  "Janis Kuvalis",
  "Everett Mayer",
  "Mrs. Jimmie Gulgowski",
  "Dr. Desiree Howell",
  "Gretchen Halvorson I",
  "Mrs. Kimberly Sawayn",
  "Kelvin Wilkinson",
  "Marianne Hayes",
  "Manuel Corwin",
  "Dr. Eleanor Koepp",
  "Rosalie Koch",
  "Holly Barrows",
  "Bruce Sanford",
  "Heather Hayes",
  "Lola Dickens",
  "Flora VonRueden",
  "Kenneth Cassin",
  "Lydia Zboncak",
  "Shelly Ryan",
  "Grady Goyette",
  "Cornelius D'Amore",
  "Mr. Irene McKenzie",
  "Amelia Armstrong",
  "Bernadette Fritsch",
  "Mrs. Matt Torp",
  "Mr. Dean Hegmann",
  "Opal Mosciski",
  "Dallas Buckridge",
  "Lois Davis",
  "Darrin Gaylord I",
  "Judy Gulgowski",
  "Ralph Ruecker PhD",
  "Geoffrey Cormier",
  "Miss Ora Metz",
  "Justin Feil",
  "Vicky Auer",
  "Dominick Walter",
  "Virgil Yost",
  "Kara Ebert",
  "Conrad Miller",
  "Paulette Spinka DVM",
  "Kristi Kihn",
  "Fred Ebert",
  "Caleb Murphy",
  "Miss Santiago Koss",
  "Moses Borer",
  "Mrs. Betsy Schaefer",
  "Wayne Zieme",
  "Brandi Ledner",
  "Mr. Wilfred Gutmann",
  "Noel Swaniawski",
  "Kelley Christiansen",
  "Ismael Gislason IV",
  "Janice Reynolds",
  "Marsha King",
  "Spencer Weissnat",
  "Mrs. Lowell Olson",
  "Chad Hamill",
  "Roman Bradtke",
  "Dave Considine",
  "Dr. Brittany Metz",
  "Stacey Waelchi",
  "Diana Monahan",
  "Mr. Ana Rowe",
  "Anita Hessel",
  "Joann Torphy",
  "Miss Floyd Lueilwitz",
  "Jane Heaney",
  "Alfred Heller",
  "Vickie Sipes",
  "Jeffery Kunde",
  "Ms. Rachel Connelly",
  "Marjorie Stokes",
  "Marion Runte II",
  "Laura Toy",
  "Miss Felix Beatty",
  "Rick Hills",
  "Vincent Casper",
  "Linda Wiegand",
  "Raymond Keebler",
  "Leo Nienow",
  "Delbert Conn",
  "Hector Torphy",
  "Wilson Emard",
  "Joann Runolfsdottir",
  "Daryl Veum",
  "Elias Ankunding",
  "Catherine Lubowitz",
  "Ruby Hermiston",
  "Traci Dickens",
  "Cora Skiles",
  "Erma Kihn",
  "Lowell Hahn",
  "Mrs. Eva Littel",
  "Jerry Hackett",
  "Patricia Jakubowski",
  "Angel DuBuque III",
  "Theodore Kiehn",
  "Hattie Carter",
  "Mr. Allan Rath",
  "Rosemarie Schiller",
  "Olive Maggio",
  "Vernon VonRueden IV",
  "Jenny Bahringer",
  "Ms. Tara Fay",
  "Erik Bins I",
  "Mae O'Hara",
  "Mrs. Kent Hermann",
  "Bridget Kessler",
  "Meredith Rath",
  "Ms. Clara Ledner",
  "Judith Bednar",
  "Roderick Farrell",
  "Terrance Simonis"
];

const _serviceAdjectives = [
  "Exceptional",
  "Licensed",
  "Convenient",
  "Cost-efficient",
  "Blazing fast",
  "Popular",
  "Awesome",
  "Comfortable",
  "Smart",
  "Intelligent",
  "Generic",
];

const _clinicNames = [
  "Floyd Medical Center",
  "Mountainside Hospital",
  "Veterans Affairs Medical Center San Diego",
  "Kenmare Community Hospital",
  "Parkview Lagrange Hospital",
  "Elliot Hospital",
  "Good Samaritan Hospital",
  "Central Alabama Veterans Health Care System East Campus",
  "Cleveland Clinic Hospital",
  "Catholic Medical Center",
  "Plantation General Hospital",
  "Yonkers General Hospital",
  "Martin General Hospital",
  "Samaritan Medical Center/Samaritan Med Ctr",
  "Wishard Memorial Hospital",
  "Jefferson Memorial Hospital",
  "Springhill Medical Center",
  "Eden Medical Center",
  "Goleta Valley Cottage Hospital",
  "Novant Health Matthews Medical Center",
  "Rome Memorial Hospital",
  "Mountain Vista Medical Center",
  "Novant Health Forsyth Medical Center",
  "Effingham Hospital",
  "Barnes-Jewish Hospital",
  "Habersham Medical Center",
  "Healthmark Regional Medical Center",
  "Mercy Gilbert Medical Center",
  "Central Alabama Veterans Health Care System East Campus",
  "Cayuga Medical Center at Ithaca",
  "Catholic Medical Center",
  "St. Mary Mercy Livonia Hospital",
  "Horizon Specialty Hospital",
  "West Palm Beach Hospital",
  "Kennedy Krieger Institute",
  "Major Hospital",
  "Mease Dunedin Hospital",
  "Sarasota Memorial Hospital",
  "George L. Mee Memorial Hospital",
  "Carondelet St. Joseph's Hospital",
  "General Leonard Wood Army Community Hospital",
  "Montclair Hospital Medical Center",
  "Providence Hospital",
  "Murphy Medical Center",
  "Brandon Regional Hospital",
  "Lake Wales Medical Center",
  "Jacobi Medical Center",
  "Presbyterian Intercommunity Hospital",
  "Perry Hospital",
  "Vegas Valley Rehabilitation Hospital",
  "Calvary Hospital",
  "Green Hospital of Scripps Clinic",
  "WellStar Cobb Hospital",
  "Rome Memorial Hospital",
  "St. Petersburg General Hospital",
  "Fairchild Medical Center",
  "Dupont Hospital",
  "Shore Memorial Hospital",
  "DeKalb Medical",
  "Deaconess Incarnate Word Health System",
  "Lee Memorial Hospital",
  "Mountainside Hospital",
  "La Palma Intercommunity Hospital",
  "Bloomington Meadows Hospital"
];
